apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend  
    
  template:
    metadata:
      labels:    
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/library/finance-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value:  postgresql://admin:secret@db:5432/finance  
