apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finance-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/idofurman/finance-dashboard
    targetRevision: HEAD
    path: finance-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
