backend:
  image:
    repository: 579083551085.dkr.ecr.us-east-1.amazonaws.com/finance-backend
    tag: latest
  port: 5000

frontend:
  image:
    repository: 579083551085.dkr.ecr.us-east-1.amazonaws.com/finance-frontend
    tag: latest

db:
  image: postgres:16
  storage: 1Gi
  storageClass: gp2

  
