apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend  
    
  template:
    metadata:
      labels:    
        app: backend
    spec:
      imagePullSecrets:
        - name: ecr-credentials
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }} 
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database-url
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: finance-secrets
                  key: anthropic-api-key
                  optional: true
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: finance-secrets
                  key: jwt-secret
            - name: ALLOWED_ORIGINS
              value: "http://52.20.107.63:30500,http://localhost:5000"
