apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storage }}
  storageClassName: {{ .Values.db.storageClass }}
