apiVersion: v1
kind: Service
metadata:
  name: exchange-rate-service
spec:
  type: ClusterIP
  selector:
    app: exchange-rate-service
  ports:
    - port: {{ .Values.exchangeRateService.port }}
      targetPort: {{ .Values.exchangeRateService.port }}
