apiVersion: v1
kind: Service
metadata:
  name: receipt-service
spec:
  type: ClusterIP
  selector:
    app: receipt-service
  ports:
    - port: {{ .Values.receiptService.port }}
      targetPort: {{ .Values.receiptService.port }}
